# Generated by Django 6.1.1 on 2026-09-29 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='education',
            field=models.TextField(blank=True, help_text='Details of degrees, certifications, and institutions'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='expected_salary',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Expected annual salary', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='experience',
            field=models.PositiveIntegerField(default=0, help_text='Total years of professional experience'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='domain',
            field=models.CharField(blank=True, help_text='e.g., IT, Healthcare, Finance', max_length=100),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='is_verified',
            field=models.BooleanField(default=False, help_text="Indicates if the company's identity has been vetted."),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='size',
            field=models.CharField(blank=True, choices=[('1-10', '1-10 employees'), ('11-50', '11-50 employees'), ('51-200', '51-200 employees'), ('201-500', '201-500 employees'), ('500+', '500+ employees')], max_length=20),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='skills',
            field=models.TextField(blank=True, help_text='Comma-separated list of skills (e.g., Python, Django, React)'),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='company_name',
            field=models.CharField(max_length=255),
        ),
    ]
