# Generated by Django 6.1.1 on 2026-09-30 06:27

import apps.users.models
import apps.users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_candidateprofile_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=apps.users.models.resume_upload_path, validators=[apps.users.validators.validate_resume_size, apps.users.validators.validate_resume_extentions]),
        ),
    ]
